---
- name: Create config files
  hosts: localhost
  gather_facts: yes
  vars:

  tasks:
    - name: Place git config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
        content: "{{ lookup('ansible.builtin.file', 'gitconfig', rstrip=false) }}"
        mode: "0644"

    - name: Place fish config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish"
        content: "{{ lookup('ansible.builtin.file', 'config.fish', rstrip=false) }}"
        mode: "0644"

    - name: Place WezTerm config file
      when: ansible_facts['os_family'] == 'Darwin'
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.wezterm.lua"
        content: "{{ lookup('ansible.builtin.file', 'wezterm.lua', rstrip=false) }}"
        mode: "0644"

    - name: Place tmux config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        content: "{{ lookup('ansible.builtin.file', 'tmux.conf', rstrip=false) }}"
        mode: "0644"

    - name: Place vim config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.vimrc"
        content: "{{ lookup('ansible.builtin.file', 'vimrc', rstrip=false) }}"
        mode: "0644"
