---
- name: Create config files
  hosts: localhost
  gather_facts: yes
  vars:

  tasks:
    - name: Place git config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
        content: "{{ lookup('ansible.builtin.file', '.gitconfig', rstrip=false) }}"
        mode: "0644"

    - name: Place fish config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish"
        content: "{{ lookup('ansible.builtin.file', 'config.fish', rstrip=false) }}"
        mode: "0644"

    - name: Place ghostty config file
      when: ansible_facts['os_family'] == 'Darwin'
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.config/ghostty/config"
        content: "{{ lookup('ansible.builtin.file', 'ghostty', rstrip=false) }}"
        mode: "0644"

    - name: Place tmux config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        content: "{{ lookup('ansible.builtin.file', 'tmux.conf', rstrip=false) }}"
        mode: "0644"

    - name: Place vim config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.vimrc"
        content: "{{ lookup('ansible.builtin.file', '.vimrc', rstrip=false) }}"
        mode: "0644"
