---
- name: Create config files
  hosts: localhost
  gather_facts: yes
  vars:

  tasks:
    - name: Place git config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
        content: "{{ lookup('ansible.builtin.file', 'gitconfig_personal') + lookup('ansible.builtin.file', 'gitconfig') }}"
        mode: '0644'

    - name: Place ghostty config file
      when: ansible_facts['os_family'] == 'Darwin'
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.config/ghostty/config"
        content: "{{ lookup('ansible.builtin.file', 'ghostty') }}"
        mode: '0644'

    - name: Place tmux config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        content: "{{ lookup('ansible.builtin.file', 'tmux') }}"
        mode: '0644'

    - name: Place tmux config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        content: "{{ lookup('ansible.builtin.file', 'tmux') }}"
        mode: '0644'

    - name: Place vim config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.vimrc"
        content: "{{ lookup('ansible.builtin.file', 'vimrc') }}"
        mode: '0644'

    - name: Place bash config file
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.bashrc"
        content: "{{ lookup('ansible.builtin.file', 'bashrc') }}"
        mode: '0644'
