theme = "base16_default"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"C-c" = "collapse_selection"
"esc" = "collapse_selection"
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"C-n" = "move_visual_line_down"
"C-p" = "move_visual_line_up"

[keys.insert]
"C-c" = "normal_mode"
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"C-n" = "move_visual_line_down"
"C-p" = "move_visual_line_up"
