[language-server.elp]
command = "/Users/williamdaughtridge/.local/share/nvim/mason/bin/elp"
args = ["server"]

[[language]]
name = "erlang"
language-servers = [ "elp" ]

[language-server.deno-language-server]
command = "deno"
args = ["lsp"]
required-root-patterns = ["deno.json", "deno.jsonc"]

[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
language-servers = ["deno-language-server"]

[[language]]
name = "javascript"
file-types = ["js", "jsx"]
language-servers = ["deno-language-server"]
