#!/usr/bin/env bash
# @location $HOME/.local/bin/tmux-lazygit-windowizer

sesh="$(tmux display-message -p '#S')"

if [ -z "$TMUX" ]; then
  exit 1
fi

if ! tmux select-window -t lazygit 2> /dev/null; then
  tmux new-window -t "$sesh" -n lazygit /opt/homebrew/bin/lazygit
else
  tmux select-window -t lazygit
fi
