#!/usr/bin/env bash

selected=$(find $HOME -mindepth 1 -maxdepth 1 -type d | fzf)

if [ -z $selected ]; then
  exit 0
fi

selected_name=$(basename $selected | tr . _)
tmux_running=$(pgrep tmux)

if [ -z $TMUX ] && [ -z $tmux_running ]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

if ! tmux switch-client -t $selected_name 2>/dev/null; then
  tmux attach-session -t $selected_name
fi

# vim: filetype=bash
