#!/usr/bin/env bash
# @location $HOME/.local/bin/tmux-terminal-sessionizer

sesh=terminal

tmux_running=(pgrep tmux)

if [ -z $TMUX ] && [ -z $tmux_running ]; then
  tmux new-session -s $sesh -c $HOME
  exit 0
fi

if ! tmux has-session -t=$sesh 2>/dev/null; then
  tmux new-session -ds $sesh -c $HOME
fi

if ! tmux switch-client -t $sesh 2>/dev/null; then
  tmux attach-session -t $sesh
fi
