theme = "rose_pine"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer"]
